package com.epherical.croptopia.common.generator;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.levelgen.feature.ConfiguredFeature;

import static com.epherical.croptopia.CroptopiaMod.createIdentifier;
import static com.epherical.croptopia.common.ItemNamesV2.*;
import static net.minecraft.core.registries.Registries.CONFIGURED_FEATURE;
import static net.minecraft.resources.ResourceKey.create;

public class ConfiguredFeatureKeys {
    public static final ResourceKey<ConfiguredFeature<?, ?>> ALMOND_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(ALMOND + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> APPLE_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(APPLE + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> APRICOT_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(APRICOT + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> AVOCADO_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(AVOCADO + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> BANANA_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(BANANA + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CASHEW_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(CASHEW + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CHERRY_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(CHERRY + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> COCONUT_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(COCONUT + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> DATE_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(DATE + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> DRAGON_FRUIT_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(DRAGONFRUIT + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> FIG_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(FIG + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> GRAPEFRUIT_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(GRAPEFRUIT + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> KUMQUAT_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(KUMQUAT + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> LEMON_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(LEMON + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> LIME_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(LIME + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> MANGO_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(MANGO + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> NECTARINE_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(NECTARINE + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> NUTMEG_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(NUTMEG + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> ORANGE_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(ORANGE + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> PEACH_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(PEACH + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> PEAR_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(PEAR + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> PECAN_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(PECAN + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> PERSIMMON_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(PERSIMMON + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> PLUM_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(PLUM + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> STAR_FRUIT_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(STARFRUIT + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> WALNUT_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(WALNUT + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CINNAMON_TREE_KEY = create(CONFIGURED_FEATURE, (createIdentifier(CINNAMON + "_tree")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> DISK_SALT_KEY = create(CONFIGURED_FEATURE, (createIdentifier("disk_salt")));
    public static final ResourceKey<ConfiguredFeature<?, ?>> RANDOM_CROP_KEY = create(CONFIGURED_FEATURE, (createIdentifier("random_crop")));

    public static final ResourceKey<ConfiguredFeature<?, ?>> ARTICHOKE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(ARTICHOKE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> ASPARAGUS_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(ASPARAGUS + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> BARLEY_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(BARLEY + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> BASIL_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(BASIL + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> BELLPEPPER_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(BELLPEPPER + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> BLACKBEAN_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(BLACKBEAN + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> BLACKBERRY_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(BLACKBERRY + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> BLUEBERRY_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(BLUEBERRY + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> BROCCOLI_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(BROCCOLI + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CABBAGE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CABBAGE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CANTALOUPE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CANTALOUPE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CAULIFLOWER_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CAULIFLOWER + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CELERY_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CELERY + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> COFFEE_BEANS_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(COFFEE_BEANS + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CORN_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CORN + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CRANBERRY_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CRANBERRY + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CUCUMBER_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CUCUMBER + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CURRANT_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CURRANT + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> EGGPLANT_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(EGGPLANT + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> ELDERBERRY_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(ELDERBERRY + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> GARLIC_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(GARLIC + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> GINGER_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(GINGER + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> GRAPE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(GRAPE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> GREENBEAN_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(GREENBEAN + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> GREENONION_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(GREENONION + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> HONEYDEW_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(HONEYDEW + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> HOPS_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(HOPS + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> KALE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(KALE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> KIWI_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(KIWI + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> LEEK_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(LEEK + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> LETTUCE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(LETTUCE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> MUSTARD_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(MUSTARD + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> OAT_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(OAT + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> OLIVE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(OLIVE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> ONION_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(ONION + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> PEANUT_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(PEANUT + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> CHILE_PEPPER_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(CHILE_PEPPER + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> PINEAPPLE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(PINEAPPLE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> RADISH_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(RADISH + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> RASPBERRY_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(RASPBERRY + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> RHUBARB_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(RHUBARB + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> RICE_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(RICE + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> RUTABAGA_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(RUTABAGA + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> SAGUARO_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(SAGUARO + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> SOYBEAN_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(SOYBEAN + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> SPINACH_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(SPINACH + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> SQUASH_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(SQUASH + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> STRAWBERRY_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(STRAWBERRY + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> SWEETPOTATO_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(SWEETPOTATO + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> TOMATILLO_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(TOMATILLO + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> TOMATO_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(TOMATO + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> TURMERIC_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(TURMERIC + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> TURNIP_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(TURNIP + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> YAM_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(YAM + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> ZUCCHINI_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(ZUCCHINI + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> VANILLA_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(VANILLA + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> PEPPER_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(PEPPER + "_crop"));
    public static final ResourceKey<ConfiguredFeature<?, ?>> TEA_LEAVES_CROP_KEY = create(CONFIGURED_FEATURE, createIdentifier(TEA_LEAVES + "_crop"));

}
