package com.epherical.croptopia.common.generator;

import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.levelgen.placement.PlacedFeature;

import static com.epherical.croptopia.CroptopiaMod.createIdentifier;
import static com.epherical.croptopia.common.ItemNamesV2.*;
import static net.minecraft.core.registries.Registries.PLACED_FEATURE;
import static net.minecraft.resources.ResourceKey.create;

public class PlacedFeatureKeys {
    public static final ResourceKey<PlacedFeature> ALMOND_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(ALMOND + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> APPLE_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(APPLE + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> APRICOT_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(APRICOT + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> AVOCADO_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(AVOCADO + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> BANANA_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(BANANA + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> CASHEW_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(CASHEW + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> CHERRY_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(CHERRY + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> COCONUT_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(COCONUT + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> DATE_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(DATE + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> DRAGONFRUIT_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(DRAGONFRUIT + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> FIG_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(FIG + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> GRAPEFRUIT_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(GRAPEFRUIT + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> KUMQUAT_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(KUMQUAT + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> LEMON_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(LEMON + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> LIME_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(LIME + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> MANGO_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(MANGO + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> NECTARINE_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(NECTARINE + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> NUTMEG_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(NUTMEG + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> ORANGE_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(ORANGE + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> PEACH_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(PEACH + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> PEAR_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(PEAR + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> PECAN_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(PECAN + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> PERSIMMON_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(PERSIMMON + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> PLUM_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(PLUM + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> STARFRUIT_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(STARFRUIT + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> WALNUT_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(WALNUT + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> CINNAMON_TREE_PLACED_KEY = create(PLACED_FEATURE, (createIdentifier(CINNAMON + "_tree_placed")));
    public static final ResourceKey<PlacedFeature> DISK_SALT_PLACED_KEY = create(PLACED_FEATURE, createIdentifier("disk_salt_placed"));

    public static final ResourceKey<PlacedFeature> ARTICHOKE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(ARTICHOKE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> ASPARAGUS_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(ASPARAGUS + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> BARLEY_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(BARLEY + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> BASIL_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(BASIL + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> BELLPEPPER_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(BELLPEPPER + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> BLACKBEAN_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(BLACKBEAN + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> BLACKBERRY_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(BLACKBERRY + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> BLUEBERRY_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(BLUEBERRY + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> BROCCOLI_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(BROCCOLI + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CABBAGE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CABBAGE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CANTALOUPE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CANTALOUPE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CAULIFLOWER_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CAULIFLOWER + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CELERY_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CELERY + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> COFFEE_BEANS_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(COFFEE_BEANS + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CORN_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CORN + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CRANBERRY_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CRANBERRY + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CUCUMBER_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CUCUMBER + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CURRANT_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CURRANT + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> EGGPLANT_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(EGGPLANT + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> ELDERBERRY_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(ELDERBERRY + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> GARLIC_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(GARLIC + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> GINGER_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(GINGER + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> GRAPE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(GRAPE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> GREENBEAN_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(GREENBEAN + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> GREENONION_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(GREENONION + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> HONEYDEW_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(HONEYDEW + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> HOPS_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(HOPS + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> KALE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(KALE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> KIWI_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(KIWI + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> LEEK_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(LEEK + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> LETTUCE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(LETTUCE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> MUSTARD_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(MUSTARD + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> OAT_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(OAT + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> OLIVE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(OLIVE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> ONION_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(ONION + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> PEANUT_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(PEANUT + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> CHILE_PEPPER_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(CHILE_PEPPER + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> PINEAPPLE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(PINEAPPLE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> RADISH_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(RADISH + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> RASPBERRY_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(RASPBERRY + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> RHUBARB_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(RHUBARB + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> RICE_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(RICE + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> RUTABAGA_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(RUTABAGA + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> SAGUARO_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(SAGUARO + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> SOYBEAN_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(SOYBEAN + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> SPINACH_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(SPINACH + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> SQUASH_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(SQUASH + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> STRAWBERRY_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(STRAWBERRY + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> SWEETPOTATO_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(SWEETPOTATO + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> TOMATILLO_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(TOMATILLO + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> TOMATO_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(TOMATO + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> TURMERIC_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(TURMERIC + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> TURNIP_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(TURNIP + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> YAM_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(YAM + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> ZUCCHINI_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(ZUCCHINI + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> VANILLA_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(VANILLA + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> PEPPER_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(PEPPER + "_crop_placed"));
    public static final ResourceKey<PlacedFeature> TEA_LEAVES_CROP_PLACED_KEY = create(PLACED_FEATURE, createIdentifier(TEA_LEAVES + "_crop_placed"));

}
